#!/bin/bash

#PBS -q default
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -N ft_swarmsize
#PBS -j oe
#PBS -m bae
#PBS –M johncarl@unm.edu

module load anaconda
module load parallel-20170322-gcc-7.1.0-csyw7ny
module load singularity3-3.0.3-gcc-7.3.0-2coe6vd

HOME_DIR="/users/johncarl/Fault-Tolerance-Drones-ARGoS/wheeler2"
cd $PBS_O_WORKDIR

TEMP_DIR=$HOME_DIR/temp
EXPERIMENTS_DIR=$HOME_DIR/experiments

CMD_STR="singularity run -B $TEMP_DIR:/root/temp/ -B $EXPERIMENTS_DIR:/faulttolerance/argos/experiments/ $PBS_O_WORKDIR/unc.simg --swarmsize {1} --perturbPlume {2} --failureProbability {3} --plumeFailureProbability {4} --seed {5} > $PBS_O_WORKDIR/results/ft_swarmsize/result_{1}_{2}_{3}_{4}_{5}.txt"

# Arena Size Coverage

mkdir -p results/ft_swarmsize

parallel $CMD_STR ::: 100 ::: false ::: 0.000001 0.0000001 ::: 0 ::: 0
